From node:16.15.1-slim

# install dependencies , ghc , cabal for compiling haskell to plutus : https://cardano.stackexchange.com/questions/9368/how-to-properly-start-a-new-plutus-project-from-scratch
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Ho_Chi_Minh
ENV PATH="/root/.ghcup/bin:$HOME/.cabal/bin:$PATH"
ENV LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
ENV PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"

WORKDIR /root/app

RUN apt-get update -y && apt-get upgrade -y && \
        apt-get install automake build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev \
                        make g++ tmux git jq wget libncursesw5 curl zsh libtool postgresql libpq-dev autoconf -y && \
        rm -rf /var/lib/apt/lists/* && \
        curl https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup > /usr/bin/ghcup && \
        chmod +x /usr/bin/ghcup && \
        ghcup install ghc 8.10.7 && ghcup set ghc 8.10.7 && \
        ghcup install cabal 3.6.2.0 && ghcup set cabal 3.6.2.0

RUN git clone https://github.com/input-output-hk/libsodium && \
        cd libsodium && \
        git checkout 66f017f1 && \
        ./autogen.sh && \
        ./configure && \
        make && make install

RUN cd /root/app && git clone https://github.com/bitcoin-core/secp256k1 && \
        cd secp256k1 && git checkout ac83be33 && \
        ./autogen.sh && \
        ./configure --enable-module-schnorrsig --enable-experimental && \
        make && make check && make install

# install aiken , marlowe-cli
COPY api/src/flatworks/shellscripts/aiken /usr/bin
RUN npm install -g @aiken-lang/aikup && aikup install
COPY api/src/flatworks/shellscripts/marlowe-cli /usr/bin

# build
ENV NODE_OPTIONS=--max_old_space_size=8192
WORKDIR /app
COPY ./ ./

#RUN yarn workspace api add cardano-addresses
RUN yarn
RUN yarn build-api

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
