version: '3'

services:
  mongo:
    image: mongo:6.0.2
    container_name: mongo
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh # for ex : "Asia/Ho_Chi_Minh"
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./dbdata:/data/db
    ports:
      - 27017:27017
    networks:
      - paasnet

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - paasnet

  api:
    image: API_MAINNET_TAG
    container_name: api
    ports:
      - 3000:3000
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh # for ex : "Asia/Ho_Chi_Minh"
    env_file:
      - .env
    command: "/bin/sh -c 'cd /app/api ; node dist/main'"
    networks:
      - paasnet

networks:
  paasnet:
    name: paasnet
    driver: bridge
