version: "3.9"  # optional since v1.27.0
services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo:/data/db

  redis:
    image: redis
    networks:
      - backend
  
networks:
  backend:
    driver: bridge